package com.edservice.SE;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-09-22T17:30:59.039+03:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://SE.edservice.com/", name = "EquityDirectServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface EquityDirectServiceImpl {

    @WebMethod
    @RequestWrapper(localName = "notifyPayment", targetNamespace = "http://SE.edservice.com/", className = "com.edservice.SE.NotifyPayment")
    @ResponseWrapper(localName = "notifyPaymentResponse", targetNamespace = "http://SE.edservice.com/", className = "com.edservice.SE.NotifyPaymentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.edservice.SE.PaymentNotificationResponse notifyPayment(
        @WebParam(name = "request", targetNamespace = "")
        com.edservice.SE.PaymentNotificationRequest request
    );

    @WebMethod
    @RequestWrapper(localName = "queryBill", targetNamespace = "http://SE.edservice.com/", className = "com.edservice.SE.QueryBill")
    @ResponseWrapper(localName = "queryBillResponse", targetNamespace = "http://SE.edservice.com/", className = "com.edservice.SE.QueryBillResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.edservice.SE.BillQueryResponse queryBill(
        @WebParam(name = "request", targetNamespace = "")
        com.edservice.SE.BillQueryRequest request
    );
}
